from . import modules_management
from . import industry_management
from . import subscription_plans_management
from . import add_ons_management
from . import res_config_settings
from . import category_management
from . import tab_category
from . import feature
from . import cron_job_sale_subscription
from . import inherit_res_user