# This is a namespace object
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: customer-name
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${CUSTOMER_NAME}
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: 748400346184.dkr.ecr.ap-southeast-1.amazonaws.com/vivesoftware:latest
        imagePullPolicy: Always
        resources:
          requests:
            ephemeral-storage: "2Gi"
            cpu: "1"
            memory: "2Gi"
          limits:
            ephemeral-storage: "4Gi"
            cpu: "1"
            memory: "2Gi"
        ports:
        - name: port8069
          containerPort: 8069
        - name: port8072
          containerPort: 8072
        env:
        - name: DB_PORT_5432_TCP_ADDR
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DB_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DB_USER
        - name: S3_ACCESS_ID
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: S3_ACCESS_ID
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: S3_SECRET_KEY
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: BUCKET_NAME
        - name: BUCKET_LOCATION
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: BUCKET_LOCATION
        - name: USER_EMAIL
          value: '${USER_EMAIL}'
        - name: SMTP_SERVER
          value: '${SMTP_SERVER}'
        - name: DOMAIN_NAME
          value: '${DOMAIN_NAME}'
      imagePullSecrets:
        - name: regcred
